services:
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: todoneo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - todoneo-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todoneo_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  todoneo-pgdata: