services:
  # todo-neo:
  #   build:
  #     context: .
  #     dockerfile: ./todoneo/src/main/docker/Dockerfile
  #   container_name: todo-neo
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todoneo_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: admin
  #   depends_on:
  #     - db

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: todoneo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - todoneo-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todoneo_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  todoneo-pgdata: